"""Session store port — chat history + video refs (Round 7)."""

from __future__ import annotations

from collections import deque
from typing import Protocol

from domain.session_types import PendingVideoText, PrevVideoRef


class SessionStorePort(Protocol):
    def get_history(self, key: str, max_pairs: int) -> deque[tuple[str, str]]: ...
    def get_prev_video(self, key: str) -> PrevVideoRef | None: ...
    def get_pending_video(self, key: str) -> PendingVideoText | None: ...
    def set_prev_video(self, key: str, ref: PrevVideoRef) -> None: ...
    def set_pending_video(self, key: str, pv: PendingVideoText) -> None: ...
    def pop_pending_video(self, key: str) -> None: ...
    def pop_prev_video(self, key: str) -> None: ...
    def clear_all(self) -> None: ...
    def ensure_session(self, key: str) -> None: ...
    def persist_session(self, key: str) -> None: ...
