"""V16 R4-B：OCR 工具错误码。"""

OCR_NOT_CONFIGURED = "ocr_not_configured"
EXTERNAL_PROCESSING_DISABLED = "external_processing_disabled"
PAID_OCR_DISABLED = "paid_ocr_disabled"
BUDGET_EXCEEDED = "budget_exceeded"
OCR_PROVIDER_ERROR = "ocr_provider_error"
OCR_EMPTY_RESULT = "ocr_empty_result"
OCR_INVALID_RESPONSE = "ocr_invalid_response"
OCR_DEPENDENCY_MISSING = "ocr_dependency_missing"
TESSERACT_NOT_INSTALLED = "tesseract_not_installed"
OCR_UNSUPPORTED_LOCAL_FORMAT = "ocr_unsupported_local_format"
OCR_FILE_TOO_LARGE = "ocr_file_too_large"
OCR_PAGE_LIMIT_EXCEEDED = "ocr_page_limit_exceeded"
